### ISSUE TITLE
Make an Entertainment Channel

### ISSUE THREAD

**Issue by mark-bruckert** [wave-tv/wave-tv#3]
Hello Github!

I need your help in fixing the Channels Component in Wave TV. I need the data from the entertainment box on the channels component to display the entertainment data instead of the news data like it is now. Below are some screenshots of the page and the firebase database:

<img width="581" alt="screen shot 2018-10-08 at 11 11 49 am" src="https://user-images.githubusercontent.com/36308014/46617570-139d4780-caeb-11e8-96af-4e94b0721976.png">

<img width="1355" alt="screen shot 2018-10-08 at 11 20 04 am" src="https://user-images.githubusercontent.com/36308014/46617979-45fb7480-caec-11e8-8a83-4b38a36bfa2e.png">

<img width="1435" alt="screen shot 2018-10-08 at 11 20 18 am" src="https://user-images.githubusercontent.com/36308014/46617980-46940b00-caec-11e8-88a1-5c4489877938.png">

**Comment by visvxplore** [comment]
#4

**Comment by visvxplore** [comment]
#4

**Comment by visvxplore** [comment]
@mark-bruckert , I made a PR #4 for this issue.

**Comment by wave-tv** [comment]
@visvxplore Thanks! Merging Now.
