### ISSUE TITLE
Play the Most Recent Videos on Both Channels

### ISSUE THREAD

**Issue by wave-tv** [wave-tv/wave-tv#5]
Hello Github!

Currently, when you attempt to play a channel, the newest video will show up on the channels screen but not in the player window. It instead chooses to show the oldest video. It needs to be showing the newest video. After playing the first video... it should continue to play older content like it does now with newer content. (Basically the order needs to be reversed)

Thanks in Advanced,
Mark

**Comment by aparrett** [comment]
I am looking into this.

**Comment by wave-tv** [comment]
@aparrett Thanks!

**Comment by am2367** [comment]
@wave-tv I suspect that this is due to your orderByChild query on firebase. That query by default returns the records in ascending order.

**Comment by wave-tv** [comment]
@am2367 How would I change this?

**Comment by am2367** [comment]
@wave-tv working on it. Give me a few to test the fix.

**Comment by aparrett** [comment]
I have submitted a pull request that fixes the issue.

**Comment by am2367** [comment]
@aparrett beat me to it with my own fix lol. I was sitting here waiting for these npm packages to install.

**Comment by aparrett** [comment]
Well, I did have a 10 minute head start 😉

**Comment by wave-tv** [comment]
@am2367 @aparrett Thanks Guys!
